name: Master Refresh

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:

  refresh-branch-code:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Install Salesforce CLI 
      - name: 'Install Salesforce CLI'
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            mkdir ~/sfdx
            tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
            echo "$HOME/sfdx/bin" >> $GITHUB_PATH
            ~/sfdx/bin/sfdx version
      # Login To ORG      
      - name: Login to org
        id: loginToOrg
        uses : sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      # Retrives all soruce data from package.xml 
      - name: Retrive from org based on package.xml
        run: sfdx force:source:retrieve -p 'force-app\main\default' -u SFDX-ENV
