name: Master Refresh

on:
  schedule:
    - cron: "*/6 * * * *"
jobs:

  refresh-branch-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Retrives all soruce data from package.xml 
      - name: Retrive from org based on package.xml
        run: sfdx force:source:retrieve -x manifest\package.xml
