name: Master Refresh

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  refresh-branch-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Install Salesforce CLI
      - name: "Install Salesforce CLI"
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
      # Login To ORG
      - name: Login to org
        id: loginToOrg
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      # Retrives all soruce data from package.xml
      - name: Retrive from org based on package.xml
        run: |
          echo Add other actions to build,
          FILE=$GITHUB_WORKSPACE/manifest/package.xml
          if test -f "$FILE"; then
              echo "$FILE exists."
          fi
          echo work space $FILE      
          sfdx force:source:retrieve -x $FILE -u SFDX-ENV
      # Commit Changes Code
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Changed by admin"
