# This is a basic workflow to help you get started with Actions

name: Test Flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: check if has metadata change
        uses: .github\actions\Check Metadata Change\action.yml
        with:
          destination-branch: ${{github.event.after}}
          source-branch: ${{github.event.before}}
          