# This is a basic workflow to help you get started with Actions

name: Test Flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_VAR : 'hello'
      TEST_VAR1 : ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: check if has metadata change
        id: checkForMetadataChange
        uses: ./.github/actions/check-metadata-change
        with:
          destination-branch: ${{github.event.after}}
          source-branch: ${{github.event.before}}                
      - name: print for metadata change
        run: echo ${{ env.TEST_VAR }}
        env:
          TEST_VAR1 : ${{ steps.checkForMetadataChange.outputs.has-metadata-change }}
      - name : test this shit
        run: |
          echo ${{ env.TEST_VAR }}
          echo ${{ env.TEST_VAR1 }}