# This is a basic workflow to help you get started with Actions

name: Test Flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
            
      #Test diff 
      - name: Delta calculate
        if: success()
        run: |
          git log --oneline -n 3
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git checkout -b pr
          git --no-pager diff --name-status pr origin/master
          sfdx sgd:source:delta --to pr --from origin/master --output .
          cat package/package.xml