# This is a basic workflow to help you get started with Actions

name: Test Flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:

  check-for-metadata-change:
    runs-on: ubuntu-latest
    outputs:
      hasChanges: 'hello'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # Check if has metadata change
      - name: check if has metadata change
        id: checkForMetadataChange
        uses: ./.github/actions/check-metadata-change
        with:
          destination-branch: ${{github.event.after}}
          source-branch: ${{github.event.before}}
      - name: Set environment variables
        run: |
         tempVar=${{steps.checkForMetadataChange.outputs.has-metadata-change}}
         echo "::set-output name=hasChanges::${tempVar}"
         echo tempVar====$tempVar

  build:

    runs-on: ubuntu-latest
    needs: check-for-metadata-change
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run a one-line script
        run: echo Hello, world!

      - name : Print Env variable of different job
        run: |

          echo prevOutputs===${{ needs.check-for-metadata-change.outputs.hasChanges }}
          echo needsDataDump === ${{toJSON(job)}}
